#!/bin/sh
set -e

echo "📂 Check if DIRS exists"
for dir in ${XDG_CONFIG_HOME} ${XDG_DATA_HOME} ${XDG_CACHE_HOME} ${XDG_RUNTIME_DIR} ${COMPOSER_CACHE_DIR}; do
  echo "📂 Check if ${dir} exists"
  if [ ! -d "${dir}" ]; then
    echo "📂 Creating ${dir}"
    mkdir -p "${dir}"
  fi
done

echo "📂 Fixing permissions XDG_*"
chown -R www-data:www-data ${XDG_CONFIG_HOME} ${XDG_DATA_HOME} ${XDG_CACHE_HOME} ${XDG_RUNTIME_DIR} ${COMPOSER_CACHE_DIR}

echo "📂 Fixing permissions app"
chown -R www-data:www-data /app